version: '3.9'
services:
  db:
    container_name: container_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=kittens_store_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: [ "sh", "./run-app.sh" ]
    ports:
      - "1234:1234"
    depends_on:
      - db
    volumes:
      - ./:/app/
    environment:
      - RACK_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/kittens_store_dev
      - POSTGRES_PASSWORD=postgres

